version: '2'

services:
  # wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 192.168.11.4:3307
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: TKBqWEnXyPniWKn4 
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-files:/var/www/html
    networks:
      - raspberrypi_network

volumes:
  wordpress-files:
    external: true

networks:
  raspberrypi_network:
    external: true

