version: '2'

services:
  https-portal:
    image: steveltn/https-portal:1.0.0
    ports:
      - '80:80'
      - '443:443'
    links:
      - wordpress
    restart: always
    environment:
      DOMAINS: 'wordpress.llasuka.synology.me -> http://wordpress:'
      # STAGE: 'production'
      # FORCE_RENEW: 'true'

  # wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: 192.168.11.4:3307
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: TKBqWEnXyPniWKn4 
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-files:/var/www/html
    networks:
      - raspberrypi_network

volumes:
  wordpress-files:
    external: true

networks:
  raspberrypi_network:
    external: true

