version: '2'

services:
  # wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    links:
      - wordpress-postgres
    restart: always
    environment:
      WORDPRESS_DB_HOST: postgres:5432
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: postgres
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-files:/var/www/html

  wordpress-postgres:
    image: postgres
    volumes:
      - wordpress-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: wordpress
      POSTGRES_PASSWORD: wordpress
      POSTGRES_USER: wordpress
volumes:
  wordpress-files:
    external: true
  wordpress-db:
    external: true

