version: '2'

services:
  wordpress-mariadb:
    image: mariadb
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  # wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - "9000:80"
    links:
      - wordpress-mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-files:/var/www/html

volumes:
  wordpress-files:
    external: true
  wordpress-db:
    external: true

